pardisopath = '[Path to libpardiso600-WIN-X86-64.lib]';

fortrancompilerpath = '[path to fortran compiler here]';

names = {'pardisoinit', 'pardisoreorder', 'pardisofactor', 'pardisosolve', 'pardisofree'};

for i = length(names)
    name = names{i};
    mex('-largeArrayDims', ['-L' 'C:\Program Files\MATLAB\R2020a\extern\lib\win64\microsoft'], '-lmwlapack', '-lmwblas',...
    ['-L' pardisopath], '-lpardiso',...
    ['-L' fortrancompilerpath],...
    '-lifcoremt', '-liomp5md',...
    'common.cpp', 'matlabmatrix.cpp', 'sparsematrix.cpp', 'pardisoinfo.cpp',...
    [name '.cpp'], '-output', name);
end

